// Generated by `npm run fonts` from resources/fonts/. Do not edit by hand.
import type { ProjectFontFace } from './types'

export const BUNDLED_FONTS: { family: string; note: string; faces: ProjectFontFace[] }[] = [
  {
    family: 'Agraham',
    note: 'Elegant display serif; its numbers are ornaments',
    faces: [{ file: 'Agraham.otf', weight: 400, italic: false }]
  },
  {
    family: 'Bebas Neue',
    note: 'Tall all-caps grotesque, made for headlines',
    faces: [{ file: 'BebasNeue-Regular.ttf', weight: 400, italic: false }]
  },
  {
    family: 'Cralika',
    note: 'Sharp editorial serif with a fashion edge',
    faces: [
      { file: 'Cralika.otf', weight: 400, italic: false },
      { file: 'Cralika-Italic.otf', weight: 400, italic: true }
    ]
  },
  {
    family: 'Gellisto',
    note: 'Friendly rounded script, hand-lettered feel',
    faces: [{ file: 'Gellisto.ttf', weight: 400, italic: false }]
  },
  {
    family: 'Gontserrat',
    note: 'Full Montserrat-style geometric family, thin to black',
    faces: [
      { file: 'Gontserrat-Thin.ttf', weight: 100, italic: false },
      { file: 'Gontserrat-ThinItalic.ttf', weight: 100, italic: true },
      { file: 'Gontserrat-ExtraLight.ttf', weight: 200, italic: false },
      { file: 'Gontserrat-ExtraLightItalic.ttf', weight: 200, italic: true },
      { file: 'Gontserrat-Light.ttf', weight: 300, italic: false },
      { file: 'Gontserrat-LightItalic.ttf', weight: 300, italic: true },
      { file: 'Gontserrat-Regular.ttf', weight: 400, italic: false },
      { file: 'Gontserrat-Italic.ttf', weight: 400, italic: true },
      { file: 'Gontserrat-Medium.ttf', weight: 500, italic: false },
      { file: 'Gontserrat-MediumItalic.ttf', weight: 500, italic: true },
      { file: 'Gontserrat-SemiBold.ttf', weight: 600, italic: false },
      { file: 'Gontserrat-SemiBoldItalic.ttf', weight: 600, italic: true },
      { file: 'Gontserrat-Bold.ttf', weight: 700, italic: false },
      { file: 'Gontserrat-BoldItalic.ttf', weight: 700, italic: true },
      { file: 'Gontserrat-ExtraBold.ttf', weight: 800, italic: false },
      { file: 'Gontserrat-ExtraBoldItalic.ttf', weight: 800, italic: true },
      { file: 'Gontserrat-Black.ttf', weight: 900, italic: false },
      { file: 'Gontserrat-BlackItalic.ttf', weight: 900, italic: true }
    ]
  },
  {
    family: 'Helvetica',
    note: 'The Swiss classic, clean and neutral',
    faces: [
      { file: 'Helvetica-Light.ttf', weight: 300, italic: false },
      { file: 'Helvetica-Regular.ttf', weight: 400, italic: false },
      { file: 'Helvetica-Oblique.ttf', weight: 400, italic: true },
      { file: 'Helvetica-Bold.ttf', weight: 700, italic: false },
      { file: 'Helvetica-BoldOblique.ttf', weight: 700, italic: true }
    ]
  },
  {
    family: 'Helvetica Compressed',
    note: 'Ultra-condensed poster caps',
    faces: [{ file: 'Helvetica-Compressed.otf', weight: 400, italic: false }]
  },
  {
    family: 'Helvetica Rounded',
    note: "Helvetica's bold cut with softened corners",
    faces: [{ file: 'HelveticaRounded-Bold.otf', weight: 700, italic: false }]
  },
  {
    family: 'Instrument Serif',
    note: 'Condensed display serif; its italic is the Sunroom short look',
    faces: [
      { file: 'InstrumentSerif-Regular.ttf', weight: 400, italic: false },
      { file: 'InstrumentSerif-Italic.ttf', weight: 400, italic: true }
    ]
  },
  {
    family: 'Loki Cola',
    note: 'Spencerian soda-script classic',
    faces: [{ file: 'LokiCola.ttf', weight: 400, italic: false }]
  },
  {
    family: 'Mermaid',
    note: 'Bold storybook serif',
    faces: [
      { file: 'Mermaid-Regular.ttf', weight: 400, italic: false },
      { file: 'Mermaid-Bold.ttf', weight: 700, italic: false }
    ]
  },
  {
    family: 'Mermaid Swash Caps',
    note: 'Mermaid with flourished capitals, for titles',
    faces: [{ file: 'MermaidSwashCaps-Bold.ttf', weight: 700, italic: false }]
  },
  {
    family: 'Min Sans',
    note: 'Modern geometric sans, dense and even',
    faces: [{ file: 'MinSans-Black.otf', weight: 900, italic: false }]
  },
  {
    family: 'Montserrat Medium',
    note: 'Geometric, a touch heavier than regular',
    faces: [{ file: 'Montserrat-Medium.ttf', weight: 500, italic: false }]
  },
  {
    family: 'Montserrat Thin',
    note: 'Hairline geometric, airy and light',
    faces: [{ file: 'Montserrat-Thin.ttf', weight: 100, italic: false }]
  },
  {
    family: 'Red Hat Display',
    note: 'Crisp open sans for titles and big words',
    faces: [
      { file: 'RedHatDisplay-Regular.ttf', weight: 400, italic: false },
      { file: 'RedHatDisplay-Italic.ttf', weight: 400, italic: true },
      { file: 'RedHatDisplay-Medium.ttf', weight: 500, italic: false },
      { file: 'RedHatDisplay-MediumItalic.ttf', weight: 500, italic: true },
      { file: 'RedHatDisplay-Bold.ttf', weight: 700, italic: false },
      { file: 'RedHatDisplay-BoldItalic.ttf', weight: 700, italic: true },
      { file: 'RedHatDisplay-Black.ttf', weight: 900, italic: false },
      { file: 'RedHatDisplay-BlackItalic.ttf', weight: 900, italic: true }
    ]
  },
  {
    family: 'Red Hat Text',
    note: 'Readable open sans for smaller sizes',
    faces: [
      { file: 'RedHatText-Regular.ttf', weight: 400, italic: false },
      { file: 'RedHatText-Italic.ttf', weight: 400, italic: true },
      { file: 'RedHatText-Medium.ttf', weight: 500, italic: false },
      { file: 'RedHatText-MediumItalic.ttf', weight: 500, italic: true },
      { file: 'RedHatText-Bold.ttf', weight: 700, italic: false },
      { file: 'RedHatText-BoldItalic.ttf', weight: 700, italic: true }
    ]
  }
]
