// Generated by `npm run luts` from resources/luts/. Do not edit by hand.

export const BUNDLED_LUTS: {
  id: string
  file: string
  name: string
  note: string
  size: number
}[] = [
  {
    id: 'aesthetic-lut',
    file: 'AestheticLut.cube',
    name: 'Aesthetic',
    note: 'Soft warm tones with a gentle fade',
    size: 16
  },
  {
    id: 'basic-grade',
    file: 'BasicGrade.cube',
    name: 'Basic Grade',
    note: 'Clean, balanced grade; a light polish',
    size: 33
  },
  {
    id: 'blue-architecture',
    file: 'BlueArchitecture.cube',
    name: 'Blue Architecture',
    note: 'Cool blues and steel, crisp city mood',
    size: 33
  },
  {
    id: 'blue-dark-vibes',
    file: 'BlueDarkVibes.cube',
    name: 'Blue Dark Vibes',
    note: 'Deep blue shadows, moody and dark',
    size: 16
  },
  {
    id: 'blue-hour',
    file: 'BlueHour.cube',
    name: 'Blue Hour',
    note: 'Dusk blues, calm and cinematic',
    size: 33
  },
  {
    id: 'cold-chrome',
    file: 'ColdChrome.cube',
    name: 'Cold Chrome',
    note: 'Cold metallic sheen, desaturated edges',
    size: 33
  },
  {
    id: 'crisp-autumn',
    file: 'CrispAutumn.cube',
    name: 'Crisp Autumn',
    note: 'Warm oranges and crunchy fall light',
    size: 33
  },
  {
    id: 'dark-aesthetic',
    file: 'DarkAesthetic.cube',
    name: 'Dark Aesthetic',
    note: 'Moody dark grade, muted and dramatic',
    size: 16
  },
  {
    id: 'dark-aesthetic-v2',
    file: 'DarkAestheticV2.cube',
    name: 'Dark Aesthetic 2',
    note: 'The same moody dark look, refined',
    size: 16
  },
  {
    id: 'dark-aesthetic-filter',
    file: 'DarkAestheticFilter.cube',
    name: 'Dark Aesthetic Filter',
    note: 'Heavy shadows with a film noir lean',
    size: 16
  },
  {
    id: 'dark-and-somber',
    file: 'DarkAndSomber.cube',
    name: 'Dark and Somber',
    note: 'Somber, low-key and grey-blue',
    size: 33
  },
  {
    id: 'hard-boost',
    file: 'HardBoost.cube',
    name: 'Hard Boost',
    note: 'Punchy contrast and saturated color',
    size: 33
  },
  {
    id: 'jof2-basic',
    file: 'Jof2Basic.cube',
    name: 'JOF Basic',
    note: 'Neutral creator grade, subtle contrast',
    size: 33
  },
  {
    id: 'jof2-low-contrast',
    file: 'Jof2LowContrast.cube',
    name: 'JOF Low Contrast',
    note: 'Low-contrast filmic softness',
    size: 33
  },
  {
    id: 'jof2-subtle-basic',
    file: 'Jof2SubtleBasic.cube',
    name: 'JOF Subtle',
    note: 'Barely-there grade, natural skin',
    size: 33
  },
  {
    id: 'long-beach-morning',
    file: 'LongBeachMorning.cube',
    name: 'Long Beach Morning',
    note: 'Soft coastal light, airy and bright',
    size: 33
  },
  {
    id: 'lush-green',
    file: 'LushGreen.cube',
    name: 'Lush Green',
    note: 'Rich greens and golden warmth',
    size: 33
  },
  {
    id: 'magic-hour',
    file: 'MagicHour.cube',
    name: 'Magic Hour',
    note: 'Golden-hour glow, warm and dreamy',
    size: 33
  },
  {
    id: 'natural-boost',
    file: 'NaturalBoost.cube',
    name: 'Natural Boost',
    note: 'A gentle lift, true to life',
    size: 33
  },
  {
    id: 'orange-and-blue',
    file: 'OrangeAndBlue.cube',
    name: 'Orange & Blue',
    note: 'Teal shadows, warm skin, blockbuster feel',
    size: 33
  },
  {
    id: 'soft-black-and-white',
    file: 'SoftBlackAndWhite.cube',
    name: 'Soft Black & White',
    note: 'Soft monochrome, gentle greys',
    size: 33
  },
  {
    id: 'waves',
    file: 'Waves.cube',
    name: 'Waves',
    note: 'Cool oceanic tint, fresh and smooth',
    size: 33
  }
]
