/**
 * Rebuilds src/shared/luts.generated.ts from the .cube files in resources/luts/ and the hand-edited
 * names/notes in resources/luts/luts.json. Run with `npm run luts`. Reads only the header of each
 * file (TITLE, LUT_3D_SIZE), stopping at the first numeric row.
 */
import { execFileSync } from 'node:child_process'
import {
  createReadStream,
  existsSync,
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync
} from 'node:fs'
import { join } from 'node:path'
import { createInterface } from 'node:readline'
import { fileURLToPath } from 'node:url'

const root = join(fileURLToPath(import.meta.url), '../..')
const lutsDir = join(root, 'resources/luts')
const overridesPath = join(lutsDir, 'luts.json')
const outPath = join(root, 'src/shared/luts.generated.ts')

type Overrides = { names?: Record<string, string>; notes?: Record<string, string> }

async function header(path: string): Promise<{ title: string | null; size: number }> {
  let title: string | null = null
  let size = 0
  const rl = createInterface({ input: createReadStream(path), crlfDelay: Infinity })
  for await (const raw of rl) {
    const line = raw.trim()
    if (/^[+-]?(?:\d|\.\d)/.test(line)) {
      rl.close()
      break
    }
    const t = /^TITLE\s+"?(.*?)"?\s*$/i.exec(line)
    if (t) title = t[1].trim() || title
    const s = /^LUT_3D_SIZE\s+(\d+)/i.exec(line)
    if (s) size = Number(s[1])
  }
  rl.close()
  return { title, size }
}

/** "BasicGrade" → "Basic Grade". */
const splitCaps = (s: string): string =>
  s.replace(/([a-z0-9])([A-Z])/g, '$1 $2').replace(/([A-Z])([A-Z][a-z])/g, '$1 $2')
const kebab = (s: string): string =>
  splitCaps(s)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')

const overrides: Overrides = existsSync(overridesPath)
  ? (JSON.parse(readFileSync(overridesPath, 'utf8')) as Overrides)
  : {}

type Lut = { id: string; file: string; name: string; note: string; size: number }
const luts: Lut[] = []
for (const entry of readdirSync(lutsDir).sort()) {
  if (entry.startsWith('._') || entry === '.DS_Store') continue
  const p = join(lutsDir, entry)
  if (statSync(p).isDirectory()) {
    if (readdirSync(p).some((f) => /\.cube$/i.test(f))) {
      console.error(`LUT file inside a subdirectory: ${entry}/ — resources/luts/ must stay flat`)
      process.exit(1)
    }
    continue
  }
  if (!/\.cube$/i.test(entry)) continue
  const stem = entry.replace(/\.cube$/i, '')
  const { title, size } = await header(p)
  if (!size) {
    console.error(`No LUT_3D_SIZE in ${entry}`)
    process.exit(1)
  }
  luts.push({
    id: kebab(stem),
    file: entry,
    name: overrides.names?.[stem] ?? title ?? splitCaps(stem),
    note: overrides.notes?.[stem] ?? 'Included with Luca',
    size
  })
  console.log(`  ${entry}: "${luts[luts.length - 1].name}", size ${size}`)
}

const missing = luts.filter((l) => !overrides.notes?.[l.file.replace(/\.cube$/i, '')])
if (missing.length)
  console.warn(
    `\nLUTs missing a note in resources/luts/luts.json (using "Included with Luca"):\n  ${missing.map((l) => l.file).join('\n  ')}`
  )

const dupes = luts.map((l) => l.id).filter((id, i, a) => a.indexOf(id) !== i)
if (dupes.length) {
  console.error(`Duplicate LUT ids: ${[...new Set(dupes)].join(', ')}`)
  process.exit(1)
}

const lines: string[] = [
  '// Generated by `npm run luts` from resources/luts/. Do not edit by hand.',
  '',
  'export const BUNDLED_LUTS: { id: string; file: string; name: string; note: string; size: number }[] = ['
]
for (const l of luts.sort((a, b) => a.name.localeCompare(b.name))) {
  lines.push(
    `  { id: ${JSON.stringify(l.id)}, file: ${JSON.stringify(l.file)}, name: ${JSON.stringify(l.name)}, note: ${JSON.stringify(l.note)}, size: ${l.size} },`
  )
}
const last = lines[lines.length - 1]
if (last.endsWith(',')) lines[lines.length - 1] = last.slice(0, -1)
lines.push(']')
writeFileSync(outPath, lines.join('\n') + '\n')
execFileSync('npx', ['prettier', '--write', outPath], { stdio: 'inherit' })
console.log(`\nWrote ${outPath} — ${luts.length} LUTs`)
